version: 2.1
jobs:
  build:
    docker:
      - image: 'phpdockerio/php:8.2-fpm'
    steps:
      - run:
          name: Install System Packages
          command: apt-get update && apt-get -y install git unzip zlib1g-dev
#      - run:
#          name: Install PHP Extensions
#          command: docker-php-ext-install pdo pdo_mysql zip
      - run:
          name: Install Composer
          command: >
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && 
            php composer-setup.php && 
            php -r "unlink('composer-setup.php');" &&
            chmod +x ./composer.phar && 
            mv ./composer.phar /usr/local/bin/composer
  deploy:
    docker:
      - image: 'phpdockerio/php:8.2-fpm'
    steps:
      - checkout
      - run:
          name: Deploy Main to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
